#!/bin/bash
# author: Qining Zhang
# date: 2018-04-19
# TEST ON Ubuntu 16.04.4 LTS & Ubuntu 14.04.5 LTS

if [[ $EUID -ne 0 ]]; then
    echo "You MUST be a root user or run with sudo" 2>&1
    exit 1
fi

apt-get update -qq
apt-get install -y libudev-dev libusb-1.0-0-dev libfox-1.6-dev git
apt-get install autotools-dev autoconf automake libtool -y

cd /tmp
git clone git://github.com/signal11/hidapi.git
cd hidapi
./bootstrap
./configure
make
make install

cd /tmp
git clone https://github.com/wjasper/Linux_Drivers.git
cd Linux_Drivers
cp 61-mcc.rules /etc/udev/rules.d
/sbin/udevadm control --reload
cd USB/mcc-libusb
make
make install
ldconfig

